# Usar a imagem oficial do nginx
FROM nginx:alpine

# Copiar os arquivos estáticos do frontend para o diretório padrão do nginx
COPY . /usr/share/nginx/html

# Expor a porta que o nginx vai rodar
EXPOSE 80
